[project]
name = "asr-pet"
version = "0.1.0"
description = "A pet project with ASR-related models"
authors = ["Vladislav Efimov <iref12@gmail.com>"]
channels = ["nvidia", "pytorch", "conda-forge", "huggingface"]
platforms = ["linux-64", "win-64"]
readme = "README.md"


[system-requirements]
cuda = "12"


[tasks]
test_imports = "python src/test_imports.py"


[target.linux-64.activation]
scripts = ["setup.sh"]


[target.win-64.activation]
scripts = ["setup.bat"]


[dependencies]
python = ">=3.11"
git = "*"
hydra-core = "*"
jupyter = "*"
more-itertools = "*"
numpy = "*"
omegaconf = "*"
plotly = "*"
polars = "*"
pyarrow = "*"
pydantic = "*"
quarto = "*"
s3fs = "*"
scikit-learn = "*"
toolz = "*"
tqdm = "*"
ruff = "*"
commitizen = "*"
mypy = "*"
pre-commit = "*"
fsspec = {version = "==2024.5.0", channel = "conda-forge"}
pytorch = {version = ">=2.3.0", channel = "pytorch"}
pytorch-cuda = {version = ">=12.0", channel = "pytorch"}
torchaudio = {version = ">=2.3.0", channel = "pytorch"}


[feature.main.dependencies]
tokenizers = {version = "*", channel = "conda-forge"}
transformers = {version = ">=4.44.0", channel = "conda-forge"}
huggingface_hub = {version = ">=0.24", channel = "conda-forge"}
datasets = {version = ">=2.19.0", channel = "conda-forge"}


[feature.main.pypi-dependencies]
nemo-toolkit = {version = "==2.0.0rc1", extras = ["asr"]}


[feature.main.tasks]
main_translate = "python src/main_test_translate.py"


[feature.custom.dependencies]
python = "<3.12"
numpy = "<2.0"
llvmlite = {version = ">=0.34.0", channel = "conda-forge"}
numba = {version = ">=0.47.0", channel = "conda-forge"}
tokenizers = {version = ">=0.13,<0.16", channel = "conda-forge"}
transformers = {version = "*", channel = "conda-forge"}


[feature.custom.pypi-dependencies]
nvidia-cublas-cu12 = "*"
nvidia-cudnn-cu12 = "<9.0.0.312"
faster-whisper = {version = ">=1.0.0"}
whisperx = {git = "https://github.com/m-bain/whisperx.git"}


[feature.custom.tasks]
custom_translate = "python src/custom_test_translate.py"


[environments]
main = ["main"]
custom = ["custom"]
default = ["main"]
